# Generated by Django 4.2.3 on 2023-07-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_searchhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
    ]
