# Generated by Django 4.2.3 on 2023-07-10 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_searchhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='language',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='source_category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='source_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
