# Generated by Django 4.2.3 on 2023-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_searchresult_image_url_searchresult_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='language',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
    ]
