# Generated by Django 4.2.3 on 2023-07-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_searchresult_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='source_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
