# Generated by Django 4.2.3 on 2023-07-10 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_searchresult_source_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
